### ISSUE TITLE
improving coding in interview

### ISSUE THREAD

**Issue by focus000** [focus000/CapacityBuilding#2]
# goal
pass Microsoft coding interview
# tasks

- [ ] pass Huawei coding exam
- [ ] complete at least 3 leetcode problems every day
- [ ] learning algorithm by books and videos
